CREATE DATABASE `sakila` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
SELECT 
	PAYMENTDATE,
    SUM(AMOUNT) AS TOTAL_AMOUNT
FROM
	PAYMENTS
GROUP BY
	PAYMENTDATE
ORDER BY
	PAYMENTDATE DESC
LIMIT 5;



SELECT
	CUSTOMERNAME,
    COUNTRY,
    AVG(CREDITLIMIT) AS AVERAGE_CREDIT
    FROM
		CUSTOMERS
	GROUP BY
		CUSTOMERNAME,
        COUNTRY;
        
        
SELECT
	PRODUCTCODE,
    QUANTITYORDERED,
    SUM(QUANTITYORDERED * PRICEEACH)
FROM
	ORDERDETAILS
GROUP BY
	PRODUCTCODE,
    QUANTITYORDERED;
    
    
SELECT
	CHECKNUMBER,
    MAX(AMOUNT) AS HIGHEST_AMOUNT
FROM
	PAYMENTS
GROUP BY
	CHECKNUMBER;
        
        
        