CREATE DATABASE STUDENTIFODB;
CREATE TABLE STUDENT (
	ID INT PRIMARY KEY,
    FULLNAME VARCHAR (100),
    AGE INT
);


INSERT INTO STUDENT (ID, FULLNAME, AGE) VALUES (1, 'JOHN DOE', 18), (2, 'JANE SMITH', 19), (3,' ADEBAYO OLUSEGUN', 21)


 UPDATE STUDENT SET AGE = 20 WHERE ID = 2;


